// infra.ts — 基础设施模板生成
import { existsSync, mkdirSync, writeFileSync } from "fs";
import { join } from "path";

export interface InfraConfig {
  dbHost: string;
  dbPort: number;
  dbUser: string;
  dbPassword: string;
  dbName: string;
  redisHost: string;
  redisPort: number;
  redisPassword: string;
  mqHost: string;
  mqPort: number;
  mqManagePort: number;
  mqUser: string;
  mqPassword: string;
}

export const DEFAULT_INFRA_CONFIG: InfraConfig = {
  dbHost: "127.0.0.1",
  dbPort: 5432,
  dbUser: "postgres",
  dbPassword: "123456",
  dbName: "fba",
  redisHost: "127.0.0.1",
  redisPort: 6379,
  redisPassword: "",
  mqHost: "127.0.0.1",
  mqPort: 5672,
  mqManagePort: 15672,
  mqUser: "guest",
  mqPassword: "guest",
};

/**
 * 生成 docker-compose.yml 内容
 */
export function generateComposeYml(
  services: string[],
  config: InfraConfig,
): string {
  const blocks: string[] = [];
  const volumes: string[] = [];

  if (services.includes("postgres")) {
    blocks.push(`  fba-postgres:
    image: postgres:16
    container_name: fba-postgres
    restart: unless-stopped
    ports:
      - "\${DB_PORT:-${config.dbPort}}:5432"
    environment:
      POSTGRES_USER: \${DB_USER:-${config.dbUser}}
      POSTGRES_PASSWORD: \${DB_PASSWORD:-${config.dbPassword}}
    volumes:
      - fba-pg-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro`);
    volumes.push("  fba-pg-data:");
  }

  if (services.includes("redis")) {
    const redisCmd = config.redisPassword
      ? `redis-server --requirepass \${REDIS_PASSWORD:-${config.redisPassword}}`
      : "redis-server";
    blocks.push(`  fba-redis:
    image: redis:7-alpine
    container_name: fba-redis
    restart: unless-stopped
    ports:
      - "\${REDIS_PORT:-${config.redisPort}}:6379"
    command: ${redisCmd}
    volumes:
      - fba-redis-data:/data`);
    volumes.push("  fba-redis-data:");
  }

  if (services.includes("rabbitmq")) {
    blocks.push(`  fba-rabbitmq:
    image: rabbitmq:3-management
    container_name: fba-rabbitmq
    restart: unless-stopped
    ports:
      - "\${MQ_PORT:-${config.mqPort}}:5672"
      - "\${MQ_MANAGE_PORT:-${config.mqManagePort}}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: \${MQ_USER:-${config.mqUser}}
      RABBITMQ_DEFAULT_PASS: \${MQ_PASSWORD:-${config.mqPassword}}
    volumes:
      - fba-mq-data:/var/lib/rabbitmq`);
    volumes.push("  fba-mq-data:");
  }

  let yml = `services:\n${blocks.join("\n\n")}\n`;
  if (volumes.length > 0) {
    yml += `\nvolumes:\n${volumes.join("\n")}\n`;
  }
  return yml;
}

/**
 * 生成 infra .env 文件
 */
export function generateInfraEnv(
  services: string[],
  config: InfraConfig,
): string {
  const lines: string[] = [];

  if (services.includes("postgres")) {
    lines.push("# PostgreSQL");
    lines.push(`DB_PORT=${config.dbPort}`);
    lines.push(`DB_USER=${config.dbUser}`);
    lines.push(`DB_PASSWORD=${config.dbPassword}`);
    lines.push("");
  }

  if (services.includes("redis")) {
    lines.push("# Redis");
    lines.push(`REDIS_PORT=${config.redisPort}`);
    lines.push(`REDIS_PASSWORD=${config.redisPassword}`);
    lines.push("");
  }

  if (services.includes("rabbitmq")) {
    lines.push("# RabbitMQ");
    lines.push(`MQ_PORT=${config.mqPort}`);
    lines.push(`MQ_MANAGE_PORT=${config.mqManagePort}`);
    lines.push(`MQ_USER=${config.mqUser}`);
    lines.push(`MQ_PASSWORD=${config.mqPassword}`);
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * 生成 PostgreSQL 初始化 SQL 脚本
 * Docker 官方 postgres 镜像会在首次启动时自动执行 /docker-entrypoint-initdb.d/ 中的脚本
 */
export function generateInitDbSql(config: InfraConfig): string {
  return `-- Auto-generated by FBA CLI
-- This script runs on first container start only

-- Create the FBA database if it doesn't exist
SELECT 'CREATE DATABASE ${config.dbName}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${config.dbName}')\\gexec

-- Connect to the database and enable extensions
\\c ${config.dbName}

-- Enable commonly used extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
`;
}

/**
 * 创建 infra 目录并写入配置文件
 */
export function createInfraDir(
  projectDir: string,
  services: string[],
  config: InfraConfig,
): void {
  const infraDir = join(projectDir, "infra");
  if (!existsSync(infraDir)) {
    mkdirSync(infraDir, { recursive: true });
  }

  writeFileSync(
    join(infraDir, "docker-compose.yml"),
    generateComposeYml(services, config),
    "utf-8",
  );
  writeFileSync(
    join(infraDir, ".env"),
    generateInfraEnv(services, config),
    "utf-8",
  );

  // 写入 PostgreSQL 初始化脚本
  if (services.includes("postgres")) {
    writeFileSync(
      join(infraDir, "init-db.sql"),
      generateInitDbSql(config),
      "utf-8",
    );
  }
}
